db.url=jdbc:mysql://localhost:3306/shtpetstore?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
db.username=root
db.password=
db.driverClassName=com.mysql.cj.jdbc.Driver

db.pool.initialSize=5
db.pool.maxActive=20
db.pool.maxWait=60000
db.pool.filters=stat,wall
