//??????db.properties
db.url=jdbc:mysql://localhost:3306
db.username=
db.password=
db.driverClassName=com.mysql.cj.jdbc.Driver

db.pool.initialSize=5
db.pool.maxActive=20
db.pool.maxWait=60000
db.pool.filters=stat,wall
